import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PostDataProvider } from "@/components/context/PostDataProvider";
import Model from "@/components/model/page";
import { ModelProvider } from "@/components/context/ModelProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PostDataProvider>
        <ModelProvider>
          <body className={inter.className}>
            <main className="flex flex-col justify-center items-center p-4">
              {children}
            </main>
            <Model />
          </body>
        </ModelProvider>
      </PostDataProvider>
    </html>
  );
}
